backend:
  name: git-gateway
  repo: k80bowman/katybowman-netlify-blog
  branch: master

media_folder: static/img
public_folder: /img
site_url: https://www.katybowman.com/
logo_url: https://www.katybowman.com/img/favicons/favicon-32x32.png

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "text"}
      - {label: "Publication", name: "publication", widget: "text", default: "none"}
      - {label: "PubLink", name: "publink", widget: "text", default: "none"}
      - {label: "ImageLink", name: "imageLink", widget: "text", default: "none"}

  - name: "experience"
    label: "Experience"
    folder: "src/pages/experience"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "experience"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Org", name: "org", widget: "string"}
      - {label: "OrgLink", name: "orgLink", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Dates", name: "dates", widget: "string"}
      - {label: "Skills", name: "skills", widget: "list"}
      - {label: "Summary", name: "summary", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/writer/index.md"
        label: "Writer"
        name: "writer"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      